# Generated by Django 4.2.7 on 2023-11-27 18:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('swiggylogin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('userId', models.UUIDField()),
                ('item', models.CharField(blank=True, max_length=100, null=True)),
                ('HotelName', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('Hotellocation', models.CharField(blank=True, max_length=100, null=True)),
                ('itemRate', models.IntegerField(blank=True, null=True)),
                ('distance', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(blank=True, max_length=100, null=True)),
                ('rate', models.CharField(blank=True, max_length=18, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='login',
            name='address',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='login',
            name='location',
            field=models.CharField(blank=True, max_length=18, null=True),
        ),
        migrations.AddField(
            model_name='login',
            name='name',
            field=models.CharField(blank=True, max_length=18, null=True),
        ),
        migrations.AddField(
            model_name='login',
            name='phonenumber',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='login',
            name='password',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='Hotels',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('restaurantName', models.CharField(max_length=100)),
                ('rating', models.CharField(max_length=100)),
                ('deliveryTime', models.CharField(blank=True, max_length=15)),
                ('cityLocation', models.CharField(blank=True, max_length=100, null=True)),
                ('distance', models.CharField(blank=True, max_length=18, null=True)),
                ('city', models.CharField(blank=True, max_length=18, null=True)),
                ('items', models.ManyToManyField(related_name='hotels', to='swiggylogin.items')),
            ],
        ),
    ]
