# Generated by Django 4.2.7 on 2023-11-27 21:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('swiggylogin', '0002_cart_items_login_address_login_location_login_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemsOrdered',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(blank=True, max_length=100, null=True)),
                ('itemCount', models.CharField(blank=True, max_length=100, null=True)),
                ('rate', models.CharField(blank=True, max_length=18, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('userId', models.UUIDField()),
                ('HotelName', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('Hotellocation', models.CharField(blank=True, max_length=100, null=True)),
                ('deliveryPerson', models.CharField(blank=True, max_length=100, null=True)),
                ('TotalItemAmount', models.IntegerField(blank=True, null=True)),
                ('TotalPay', models.IntegerField(blank=True, null=True)),
                ('orderStatus', models.CharField(blank=True, max_length=100, null=True)),
                ('item', models.ManyToManyField(related_name='OrderedItems', to='swiggylogin.itemsordered')),
            ],
        ),
    ]
