# Generated by Django 4.2.7 on 2023-11-27 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swiggylogin', '0003_itemsordered_orderdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdata',
            name='totalItems',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
