# Generated by Django 4.2.7 on 2023-11-27 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swiggylogin', '0008_alter_itemsordered_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemsordered',
            name='item',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
