# Generated by Django 4.2.7 on 2023-11-28 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swiggylogin', '0009_alter_itemsordered_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='deliveryTime',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
