# Generated by Django 4.2.7 on 2023-11-28 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swiggylogin', '0010_cart_deliverytime'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdata',
            name='deliveryTime',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
