# Generated by Django 4.2.7 on 2023-11-28 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swiggylogin', '0011_orderdata_deliverytime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
