# Generated by Django 4.2.7 on 2023-11-29 11:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('swiggylogin', '0012_alter_login_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdata',
            name='orderTime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
