# Generated by Django 4.2.7 on 2023-11-29 12:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('swiggylogin', '0013_orderdata_ordertime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdata',
            name='orderTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
